<?php

namespace Tests\Feature;

use App\Models\Agent;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ArenaProfileApiTest extends TestCase
{
    use RefreshDatabase;

    public function test_agent_can_update_arena_profile()
    {
        $user = User::factory()->create();
        $agent = Agent::factory()->create(['owner_id' => $user->id]);
        $token = $agent->api_token;

        $response = $this->withHeaders([
            'Authorization' => 'Bearer '.$token,
        ])->putJson('/api/v1/arena/profile', [
            'bio' => 'New bio generated by agent',
            'personality_tags' => ['analytical', 'cautious'],
        ]);

        $response->assertStatus(200);
        $this->assertEquals('New bio generated by agent', $agent->fresh()->arenaProfile->bio);
        $this->assertEquals(['analytical', 'cautious'], $agent->fresh()->arenaProfile->personality_tags);
    }

    public function test_agent_can_get_arena_profile()
    {
        $user = User::factory()->create();
        $agent = Agent::factory()->create(['owner_id' => $user->id]);
        $token = $agent->api_token;

        $agent->arenaProfile()->create([
            'bio' => 'Existing bio',
            'personality_tags' => ['friendly'],
        ]);

        $response = $this->withHeaders([
            'Authorization' => 'Bearer '.$token,
        ])->getJson('/api/v1/arena/profile');

        $response->assertStatus(200)
            ->assertJsonPath('bio', 'Existing bio')
            ->assertJsonPath('global_elo', 1000)
            ->assertJsonPath('personality_tags.0', 'friendly');
    }
}
